import React from "react";
import {
  View,
  Text,
  ScrollView,
  StyleSheet,
  TouchableOpacity,
} from "react-native";
import Ionicons from "@expo/vector-icons/Ionicons";
import { useNavigation } from "@react-navigation/native";

const AboutService = () => {
    const navigation = useNavigation();
  return (
    <View style={{ flex: 1, backgroundColor: "#D9E4EC", padding: 16 }}>
      <TouchableOpacity style={{marginBottom:10}} onPress={() => navigation.navigate("Default Home")}>
        <Ionicons name="arrow-back-circle" size={40} color="#003366" />
      </TouchableOpacity>
      <ScrollView style={styles.container}>
        <View style={styles.header}>
          <Text style={styles.title}>Welcome to CareConnect</Text>
          <Text style={styles.subtitle}>Your Digital Healthcare Assistant</Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>About CareConnect</Text>
          <Text style={styles.sectionText}>
            CareConnect is an innovative healthcare platform designed to connect
            patients and healthcare providers efficiently. Our app provides a
            seamless experience for managing your health records, scheduling
            appointments, and accessing vital health information.
          </Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Our Services</Text>
          <Text style={styles.serviceTitle}>1. Medical History Management</Text>
          <Text style={styles.sectionText}>
            Keep track of your medical history, prescriptions, and lab results
            in one secure place. Our app ensures your records are accessible by
            authorized healthcare providers for better decision-making.
          </Text>

          <Text style={styles.serviceTitle}>2. Appointment Scheduling</Text>
          <Text style={styles.sectionText}>
            Easily schedule appointments with your preferred healthcare
            provider. Get notified about upcoming appointments and avoid the
            hassle of waiting in long queues.
          </Text>

          <Text style={styles.serviceTitle}>3. Emergency SOS System</Text>
          <Text style={styles.sectionText}>
            In case of an emergency, use the SOS feature to notify nearby
            hospitals and emergency contacts. This feature ensures rapid
            response during critical times.
          </Text>

          <Text style={styles.serviceTitle}>
            4. QR Code Medical History Sharing
          </Text>
          <Text style={styles.sectionText}>
            Share your medical history securely with hospital staff by scanning
            the QR code generated by the app. This feature eliminates the need
            for carrying physical documents.
          </Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Why Choose CareConnect?</Text>
          <Text style={styles.sectionText}>
            Our goal is to make healthcare more accessible, secure, and
            convenient for everyone. Whether you're a patient managing your
            health records or a healthcare provider looking for better ways to
            serve your patients, CareConnect has the right tools to enhance your
            experience.
          </Text>

          <Text style={styles.bulletPoint}>
            - Easy access to medical history
          </Text>
          <Text style={styles.bulletPoint}>
            - Secure sharing of medical records
          </Text>
          <Text style={styles.bulletPoint}>
            - Real-time appointment management
          </Text>
          <Text style={styles.bulletPoint}>
            - Advanced security for sensitive data
          </Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>
            Start Using CareConnect Today!
          </Text>
          <Text style={styles.sectionText}>
            Join our community of patients and healthcare providers and take
            control of your health with CareConnect.
          </Text>
        </View>
      </ScrollView>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: 16,
    paddingBottom:20
  },
  header: {
    backgroundColor: "#003366",
    padding: 20,
    borderRadius: 8,
    marginBottom: 20,
  },
  title: {
    fontSize: 28,
    color: "#FFFFFF",
    fontWeight: "bold",
    textAlign: "center",
  },
  subtitle: {
    fontSize: 18,
    color: "#FFFFFF",
    textAlign: "center",
    marginTop: 5,
  },
  section: {
    backgroundColor: "#FFFFFF",
    padding: 16,
    borderRadius: 8,
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#003366",
    marginBottom: 10,
  },
  sectionText: {
    fontSize: 16,
    color: "#333333",
    lineHeight: 22,
  },
  serviceTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#003366",
    marginTop: 10,
    marginBottom: 5,
  },
  bulletPoint: {
    fontSize: 16,
    color: "#333333",
    marginLeft: 10,
    marginTop: 5,
  },
});

export default AboutService;
